server:
  port: 5000

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/project
      username: root
      password: root

jwt:
  access-secret: "access-secret-access-secret-access-secret-access-secret-access-secret-access-secret-access-secret"
  refresh-secret: "refresh-secret-refresh-secret-refresh-secret-refresh-secret-refresh-secret-refresh-secret-refresh-secret"
  # access-token is valid 24 hours
  access-token-validity-in-seconds: 86400
  # refresh-token is valid 30 days
  refresh-token-validity-in-seconds: 2592000